services:
  ocean-market:
    image: oceanenterprise/market:latest
    platform: linux/amd64
    container_name: ocean-market
    ports:
      - '8008:8008'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
